#!/usr/bin/env python3
"""
Sastre Chain Generator
======================
Generates Sastre automation chains from section templates.
Reads `section_templates.json` and produces standard investigation scripts.
"""

import json
import os
from pathlib import Path

TEMPLATES_PATH = Path("/Users/attic/01. DRILL_SEARCH/drill-search-app/.claude/skills/edith-templates/mined/section_templates.json")
OUTPUT_DIR = Path("/Users/attic/01. DRILL_SEARCH/drill-search-app/BACKEND/modules/SASTRE/chains")

def load_templates():
    if not TEMPLATES_PATH.exists():
        print(f"Error: {TEMPLATES_PATH} not found.")
        return {}
    with open(TEMPLATES_PATH) as f:
        return json.load(f)

def generate_chain_for_type(section_type, templates):
    """
    Generates a Sastre script for a specific section type (e.g. 'biographical').
    Aggregates logic from all templates of that type.
    """
    
    script = []
    script.append(f"// AUTOMATED CHAIN FOR: {section_type.upper()}")
    script.append("// Generated by Sastre Chain Generator")
    script.append("")
    
    # 1. Initialization
    script.append('SET $subject = "TARGET_ENTITY"')
    script.append("")
    
    # 2. Determine Sources & Actions based on templates
    all_sources = set()
    all_phrases = set()
    
    for t in templates:
        for s in t.get("data_sources_used", []):
            all_sources.add(s.lower())
        for p in t.get("key_phrases", []):
            all_phrases.add(p)

    # 3. Build Logic
    
    # Registry/Corporate Logic
    if any(x in str(all_sources) for x in ["registry", "corporate", "filing", "company"]):
        script.append("// Corporate Registry Check")
        script.append('$corp_data = cuk: $subject :cuk! => @company?')
        script.append("IF $corp_data.exists THEN")
        script.append('  LOG "Corporate record found."')
        script.append("ELSE")
        script.append('  LOG "No corporate record found."')
        script.append("END")
        script.append("")

    # Property/Asset Logic
    if any(x in str(all_sources) for x in ["land", "property", "estate", "asset"]):
        script.append("// Asset/Property Check")
        script.append('$assets = $subject => :assuk! => @property?')
        script.append("")

    # News/Media Logic (using key phrases)
    if all_phrases:
        script.append("// Adverse Media / Key Phrase Check")
        # Construct OR query
        phrases_list = [f'\"{p}\"' for p in list(all_phrases)[:5]] # Limit to top 5 to avoid huge strings
        query = " OR ".join(phrases_list)
        script.append(f'$media_hits = $subject => news: {query} => topicType:risk')
        script.append("")

    # 4. Narrative Generation (via EDITh)
    script.append("// Generate Narrative via EDITh")
    script.append(f'WRITE template "{section_type}_combined"')
    script.append('  WITH context($subject, $corp_data, $assets, $media_hits)')
    script.append(f'  => OUT section "{section_type.replace("_", " ").title()}"')
    
    return "\n".join(script)

def main():
    data = load_templates()
    templates_by_type = data.get("templates_by_type", {})
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    generated_count = 0
    
    # Generate for each type
    for section_type, type_data in templates_by_type.items():
        templates = type_data.get("templates", [])
        if not templates: continue
        
        chain_script = generate_chain_for_type(section_type, templates)
        
        filename = f"{section_type}.sastre"
        with open(OUTPUT_DIR / filename, "w") as f:
            f.write(chain_script)
            
        generated_count += 1
        
    print(f"Generated {generated_count} Sastre chains in {OUTPUT_DIR}")

    # Generate the requested specific DD UK chain manually as a gold standard
    generate_dd_uk_gold_standard()

def generate_dd_uk_gold_standard():
    """Generates the specific EDITH DD UK chain requested by the user."""
    script = """// SASTRE CHAIN: EDITH DD UK (Gold Standard)
// Full End-to-End Due Diligence for UK Entities

// 1. SETUP
SET $subject = "TARGET_COMPANY"
SET $jurisdiction = "UK"

// 2. IDENTITY & REGISTRY
// Full sweep of UK registries (Companies House + Torpedo)
$corp_node = cuk: $subject :cuk! 
  => @company? 
  => #TARGET_CORP

IF $corp_node.exists THEN
  LOG "Target identified in registry."

  // 3. MANAGEMENT (Officers)
  $officers = $corp_node => officers! 
    => @person? 
    => +#MANAGEMENT

  // 4. OWNERSHIP (PSCs)
  $owners = $corp_node => shareholders! 
    => @entity? 
    => +#OWNERSHIP

  // 5. FINANCIALS
  $financials = $corp_node => filings! 
    => @document?
    => +#FINANCIALS

  // 6. ASSETS (UK Land Registry)
  $assets = $subject => :assuk! 
    => @property? 
    => +#ASSETS

  // 7. RISK CHECK
  $risk_hits = ($subject OR $officers) => news: "fraud" OR "litigation" OR "sanction" OR "money laundering"
    => topicType:risk 
    => +#ADVERSE_MEDIA

  // 8. SANCTIONS
  $sanctions = ($corp_node OR $officers OR $owners) => chain: sanctions_check 
    => +#SANCTIONS_HIT

  // 9. NARRATIVE GENERATION
  WRITE template "dd_uk_full_report" 
    WITH context($corp_node, $officers, $owners, $financials, $assets, $risk_hits, $sanctions)
    => OUT report "Due Diligence Report: " + $subject

ELSE
  LOG "Target NOT found. Aborting."
  WRITE template "dd_uk_not_found" WITH context($subject)
END
"""
    with open(OUTPUT_DIR / "EDITH_DD_UK.sastre", "w") as f:
        f.write(script)
    print(f"Generated Gold Standard chain: {OUTPUT_DIR / 'EDITH_DD_UK.sastre'}")

if __name__ == "__main__":
    main()
